name: Hello GitHub Actions

on:
  push:
    branches: [ "main" ]
  # I added the pull request
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello Script
        run: python hello.py

      # Testing steps
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest
